// Code generated by MockGen. DO NOT EDIT.
// Source: workflow/workflow.go

// Package workflow is a generated GoMock package.
package workflow

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWorkflow is a mock of Workflow interface.
type MockWorkflow struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowMockRecorder
}

// MockWorkflowMockRecorder is the mock recorder for MockWorkflow.
type MockWorkflowMockRecorder struct {
	mock *MockWorkflow
}

// NewMockWorkflow creates a new mock instance.
func NewMockWorkflow(ctrl *gomock.Controller) *MockWorkflow {
	mock := &MockWorkflow{ctrl: ctrl}
	mock.recorder = &MockWorkflowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflow) EXPECT() *MockWorkflowMockRecorder {
	return m.recorder
}

// IsExternal mocks base method.
func (m *MockWorkflow) IsExternal() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExternal")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsExternal indicates an expected call of IsExternal.
func (mr *MockWorkflowMockRecorder) IsExternal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExternal", reflect.TypeOf((*MockWorkflow)(nil).IsExternal))
}

// MaxRetries mocks base method.
func (m *MockWorkflow) MaxRetries() int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxRetries")
	ret0, _ := ret[0].(int32)
	return ret0
}

// MaxRetries indicates an expected call of MaxRetries.
func (mr *MockWorkflowMockRecorder) MaxRetries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxRetries", reflect.TypeOf((*MockWorkflow)(nil).MaxRetries))
}

// String mocks base method.
func (m *MockWorkflow) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockWorkflowMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockWorkflow)(nil).String))
}

// Version mocks base method.
func (m *MockWorkflow) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockWorkflowMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockWorkflow)(nil).Version))
}

// WorkflowName mocks base method.
func (m *MockWorkflow) WorkflowName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkflowName")
	ret0, _ := ret[0].(string)
	return ret0
}

// WorkflowName indicates an expected call of WorkflowName.
func (mr *MockWorkflowMockRecorder) WorkflowName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkflowName", reflect.TypeOf((*MockWorkflow)(nil).WorkflowName))
}

// MockWorkflowRepository is a mock of WorkflowRepository interface.
type MockWorkflowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowRepositoryMockRecorder
}

// MockWorkflowRepositoryMockRecorder is the mock recorder for MockWorkflowRepository.
type MockWorkflowRepositoryMockRecorder struct {
	mock *MockWorkflowRepository
}

// NewMockWorkflowRepository creates a new mock instance.
func NewMockWorkflowRepository(ctrl *gomock.Controller) *MockWorkflowRepository {
	mock := &MockWorkflowRepository{ctrl: ctrl}
	mock.recorder = &MockWorkflowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowRepository) EXPECT() *MockWorkflowRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWorkflowRepository) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockWorkflowRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWorkflowRepository)(nil).Close))
}

// CreateWorkflowExecution mocks base method.
func (m *MockWorkflowRepository) CreateWorkflowExecution(arg0 string, arg1 WorkflowExecution) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateWorkflowExecution", arg0, arg1)
}

// CreateWorkflowExecution indicates an expected call of CreateWorkflowExecution.
func (mr *MockWorkflowRepositoryMockRecorder) CreateWorkflowExecution(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkflowExecution", reflect.TypeOf((*MockWorkflowRepository)(nil).CreateWorkflowExecution), arg0, arg1)
}

// DeepDownstreams mocks base method.
func (m *MockWorkflowRepository) DeepDownstreams(id, version string) map[string]bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeepDownstreams", id, version)
	ret0, _ := ret[0].(map[string]bool)
	return ret0
}

// DeepDownstreams indicates an expected call of DeepDownstreams.
func (mr *MockWorkflowRepositoryMockRecorder) DeepDownstreams(id, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeepDownstreams", reflect.TypeOf((*MockWorkflowRepository)(nil).DeepDownstreams), id, version)
}

// DeepUpstreams mocks base method.
func (m *MockWorkflowRepository) DeepUpstreams(id, version string) map[string]bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeepUpstreams", id, version)
	ret0, _ := ret[0].(map[string]bool)
	return ret0
}

// DeepUpstreams indicates an expected call of DeepUpstreams.
func (mr *MockWorkflowRepositoryMockRecorder) DeepUpstreams(id, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeepUpstreams", reflect.TypeOf((*MockWorkflowRepository)(nil).DeepUpstreams), id, version)
}

// Downstreams mocks base method.
func (m *MockWorkflowRepository) Downstreams(id, version string) map[string]bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Downstreams", id, version)
	ret0, _ := ret[0].(map[string]bool)
	return ret0
}

// Downstreams indicates an expected call of Downstreams.
func (mr *MockWorkflowRepositoryMockRecorder) Downstreams(id, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Downstreams", reflect.TypeOf((*MockWorkflowRepository)(nil).Downstreams), id, version)
}

// Executions mocks base method.
func (m *MockWorkflowRepository) Executions(id, version string) map[string]WorkflowExecution {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Executions", id, version)
	ret0, _ := ret[0].(map[string]WorkflowExecution)
	return ret0
}

// Executions indicates an expected call of Executions.
func (mr *MockWorkflowRepositoryMockRecorder) Executions(id, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Executions", reflect.TypeOf((*MockWorkflowRepository)(nil).Executions), id, version)
}

// Fetch mocks base method.
func (m *MockWorkflowRepository) Fetch(id, version string) (WorkflowInstance, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", id, version)
	ret0, _ := ret[0].(WorkflowInstance)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockWorkflowRepositoryMockRecorder) Fetch(id, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockWorkflowRepository)(nil).Fetch), id, version)
}

// RequiredBy mocks base method.
func (m *MockWorkflowRepository) RequiredBy(e, required, version string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequiredBy", e, required, version)
}

// RequiredBy indicates an expected call of RequiredBy.
func (mr *MockWorkflowRepositoryMockRecorder) RequiredBy(e, required, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequiredBy", reflect.TypeOf((*MockWorkflowRepository)(nil).RequiredBy), e, required, version)
}

// Requires mocks base method.
func (m *MockWorkflowRepository) Requires(e, required, version string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Requires", e, required, version)
}

// Requires indicates an expected call of Requires.
func (mr *MockWorkflowRepositoryMockRecorder) Requires(e, required, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Requires", reflect.TypeOf((*MockWorkflowRepository)(nil).Requires), e, required, version)
}

// RevertRequires mocks base method.
func (m *MockWorkflowRepository) RevertRequires(e, required, version string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RevertRequires", e, required, version)
}

// RevertRequires indicates an expected call of RevertRequires.
func (mr *MockWorkflowRepositoryMockRecorder) RevertRequires(e, required, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertRequires", reflect.TypeOf((*MockWorkflowRepository)(nil).RevertRequires), e, required, version)
}

// Upsert mocks base method.
func (m *MockWorkflowRepository) Upsert(instance WorkflowInstance) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Upsert", instance)
}

// Upsert indicates an expected call of Upsert.
func (mr *MockWorkflowRepositoryMockRecorder) Upsert(instance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockWorkflowRepository)(nil).Upsert), instance)
}

// Upstreams mocks base method.
func (m *MockWorkflowRepository) Upstreams(id, version string) map[string]bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upstreams", id, version)
	ret0, _ := ret[0].(map[string]bool)
	return ret0
}

// Upstreams indicates an expected call of Upstreams.
func (mr *MockWorkflowRepositoryMockRecorder) Upstreams(id, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upstreams", reflect.TypeOf((*MockWorkflowRepository)(nil).Upstreams), id, version)
}

// MockWorkflowInstance is a mock of WorkflowInstance interface.
type MockWorkflowInstance struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowInstanceMockRecorder
}

// MockWorkflowInstanceMockRecorder is the mock recorder for MockWorkflowInstance.
type MockWorkflowInstanceMockRecorder struct {
	mock *MockWorkflowInstance
}

// NewMockWorkflowInstance creates a new mock instance.
func NewMockWorkflowInstance(ctrl *gomock.Controller) *MockWorkflowInstance {
	mock := &MockWorkflowInstance{ctrl: ctrl}
	mock.recorder = &MockWorkflowInstanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowInstance) EXPECT() *MockWorkflowInstanceMockRecorder {
	return m.recorder
}

// AddParameters mocks base method.
func (m *MockWorkflowInstance) AddParameters(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddParameters", key, value)
}

// AddParameters indicates an expected call of AddParameters.
func (mr *MockWorkflowInstanceMockRecorder) AddParameters(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddParameters", reflect.TypeOf((*MockWorkflowInstance)(nil).AddParameters), key, value)
}

// DecRetry mocks base method.
func (m *MockWorkflowInstance) DecRetry() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DecRetry")
}

// DecRetry indicates an expected call of DecRetry.
func (mr *MockWorkflowInstanceMockRecorder) DecRetry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecRetry", reflect.TypeOf((*MockWorkflowInstance)(nil).DecRetry))
}

// Execute mocks base method.
func (m *MockWorkflowInstance) Execute() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockWorkflowInstanceMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockWorkflowInstance)(nil).Execute))
}

// GetPartition mocks base method.
func (m *MockWorkflowInstance) GetPartition() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPartition")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPartition indicates an expected call of GetPartition.
func (mr *MockWorkflowInstanceMockRecorder) GetPartition() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPartition", reflect.TypeOf((*MockWorkflowInstance)(nil).GetPartition))
}

// GetStatus mocks base method.
func (m *MockWorkflowInstance) GetStatus() Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(Status)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockWorkflowInstanceMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockWorkflowInstance)(nil).GetStatus))
}

// IncRetry mocks base method.
func (m *MockWorkflowInstance) IncRetry() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRetry")
}

// IncRetry indicates an expected call of IncRetry.
func (mr *MockWorkflowInstanceMockRecorder) IncRetry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRetry", reflect.TypeOf((*MockWorkflowInstance)(nil).IncRetry))
}

// InstanceId mocks base method.
func (m *MockWorkflowInstance) InstanceId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceId")
	ret0, _ := ret[0].(string)
	return ret0
}

// InstanceId indicates an expected call of InstanceId.
func (mr *MockWorkflowInstanceMockRecorder) InstanceId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceId", reflect.TypeOf((*MockWorkflowInstance)(nil).InstanceId))
}

// IsExternal mocks base method.
func (m *MockWorkflowInstance) IsExternal() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExternal")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsExternal indicates an expected call of IsExternal.
func (mr *MockWorkflowInstanceMockRecorder) IsExternal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExternal", reflect.TypeOf((*MockWorkflowInstance)(nil).IsExternal))
}

// MaxRetries mocks base method.
func (m *MockWorkflowInstance) MaxRetries() int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxRetries")
	ret0, _ := ret[0].(int32)
	return ret0
}

// MaxRetries indicates an expected call of MaxRetries.
func (mr *MockWorkflowInstanceMockRecorder) MaxRetries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxRetries", reflect.TypeOf((*MockWorkflowInstance)(nil).MaxRetries))
}

// Parameters mocks base method.
func (m *MockWorkflowInstance) Parameters() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DParameters")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Parameters indicates an expected call of Parameters.
func (mr *MockWorkflowInstanceMockRecorder) Parameters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DParameters", reflect.TypeOf((*MockWorkflowInstance)(nil).Parameters))
}

// Retries mocks base method.
func (m *MockWorkflowInstance) Retries() int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retries")
	ret0, _ := ret[0].(int32)
	return ret0
}

// Retries indicates an expected call of Retries.
func (mr *MockWorkflowInstanceMockRecorder) Retries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retries", reflect.TypeOf((*MockWorkflowInstance)(nil).Retries))
}

// SetStatus mocks base method.
func (m *MockWorkflowInstance) SetStatus(arg0 Status) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", arg0)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockWorkflowInstanceMockRecorder) SetStatus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockWorkflowInstance)(nil).SetStatus), arg0)
}

// String mocks base method.
func (m *MockWorkflowInstance) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockWorkflowInstanceMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockWorkflowInstance)(nil).String))
}

// Target mocks base method.
func (m *MockWorkflowInstance) Target() DataEndpoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Target")
	ret0, _ := ret[0].(DataEndpoint)
	return ret0
}

// Target indicates an expected call of Target.
func (mr *MockWorkflowInstanceMockRecorder) Target() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Target", reflect.TypeOf((*MockWorkflowInstance)(nil).Target))
}

// Version mocks base method.
func (m *MockWorkflowInstance) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockWorkflowInstanceMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockWorkflowInstance)(nil).Version))
}

// WorkflowName mocks base method.
func (m *MockWorkflowInstance) WorkflowName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkflowName")
	ret0, _ := ret[0].(string)
	return ret0
}

// WorkflowName indicates an expected call of WorkflowName.
func (mr *MockWorkflowInstanceMockRecorder) WorkflowName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkflowName", reflect.TypeOf((*MockWorkflowInstance)(nil).WorkflowName))
}

// MockDataEndpoint is a mock of DataEndpoint interface.
type MockDataEndpoint struct {
	ctrl     *gomock.Controller
	recorder *MockDataEndpointMockRecorder
}

// MockDataEndpointMockRecorder is the mock recorder for MockDataEndpoint.
type MockDataEndpointMockRecorder struct {
	mock *MockDataEndpoint
}

// NewMockDataEndpoint creates a new mock instance.
func NewMockDataEndpoint(ctrl *gomock.Controller) *MockDataEndpoint {
	mock := &MockDataEndpoint{ctrl: ctrl}
	mock.recorder = &MockDataEndpointMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataEndpoint) EXPECT() *MockDataEndpointMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockDataEndpoint) Exists() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockDataEndpointMockRecorder) Exists() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockDataEndpoint)(nil).Exists))
}

// Name mocks base method.
func (m *MockDataEndpoint) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockDataEndpointMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockDataEndpoint)(nil).Name))
}
